<section class="pane" id="pane-seguridad">
    <div class="pane-guide-bar"><button type="button" class="privacy-guide-trigger" data-guide-open="seguridad" aria-haspopup="dialog">? Instructivo de Seguridad</button></div>
    <div class="split"><div>
        <section class="card"><h3 style="margin-top:0">Gobierno y RACI</h3><?php foreach($securityAssignments as $assignment): ?><div class="list-row"><strong><?= esc($assignment['rol']) ?></strong> · <?= esc($assignment['responsable']) ?><div class="mini"><?= esc($assignment['acto_designacion'] ?? '') ?></div></div><?php endforeach; ?><form method="post" action="<?= base_url($basePath . '/seguridad/asignaciones') ?>"><?= csrf_field() ?><label>Rol</label><select name="rol"><?php foreach(['organo','administrador','opd','ti','seguridad_fisica'] as $v): ?><option><?= $v ?></option><?php endforeach; ?></select><label>Persona o area responsable</label><input name="responsable" required><label>Acto o evidencia de designacion</label><input name="acto_designacion"><button class="btn btn-primary" type="submit">Registrar responsabilidad</button></form></section>
        <section class="card"><h3 style="margin-top:0">Evidencias de controles</h3><?php foreach($securityControls as $control): ?><div class="list-row"><strong><?= esc(str_replace('_',' ',$control['tipo'])) ?></strong> <span class="badge <?= $control['resultado']==='conforme'?'badge-on':'badge-off' ?>"><?= esc($control['resultado']) ?></span><div class="mini"><?= esc($control['ejecutado_at']) ?> · vence <?= esc($control['vence_at']??'sin fecha') ?> · hash <?= esc($control['evidencia_hash']) ?></div></div><?php endforeach; ?><form method="post" action="<?= base_url($basePath . '/seguridad/controles') ?>"><?= csrf_field() ?><label>Control</label><select name="tipo"><?php foreach(['matriz_riesgos','revision_accesos','prueba_restauracion','capacitacion','evaluacion_encargados','rotacion_secretos','prueba_filtro_ia','auditoria','mfa_roles_criticos','segregacion_clientes'] as $v): ?><option value="<?= $v ?>"><?= str_replace('_',' ',$v) ?></option><?php endforeach; ?></select><label>Resultado</label><select name="resultado"><option>conforme</option><option>no_conforme</option></select><label>Vigente hasta</label><input type="date" name="vence_at"><label>Evidencia o acta</label><input name="evidencia" required><label>Detalle verificable</label><textarea name="detalle" required></textarea><button class="btn btn-primary" type="submit">Sellar evidencia</button></form></section>
    </div><div><form class="card" method="post" action="<?= base_url($basePath . '/seguridad/incidentes') ?>"><?= csrf_field() ?><h3 style="margin-top:0">Registrar incidente</h3><label>Tipo</label><input name="tipo" value="seguridad_datos"><label>Severidad</label><select name="severidad"><option>S1</option><option>S2</option><option>S3</option><option selected>S4</option></select><label>Fuente</label><input name="fuente"><label>Fecha de deteccion</label><input type="datetime-local" name="detectado_at"><label>Fecha de conocimiento del area</label><input type="datetime-local" name="conocimiento_at" required><label>Descripcion</label><textarea name="detalle" required></textarea><button class="btn btn-danger" type="submit">Abrir expediente</button></form></div></div>
    <h3>Expedientes de incidentes</h3><?php foreach($securityIncidents as $incident): $incidentOver=$incident['estado']!=='cerrado'&&!empty($incident['sic_vence_at'])&&$incident['sic_vence_at']<date('Y-m-d'); ?><details class="card"><summary><strong><?= esc($incident['folio']??('INC-'.$incident['id'])) ?></strong> · <?= esc($incident['severidad']) ?> <span class="badge <?= $incident['estado']==='cerrado'?'badge-on':($incidentOver?'badge-off':'') ?>"><?= esc($incident['estado']) ?></span> <span class="mini <?= $incidentOver?'deadline-over':'' ?>">SIC: <?= esc($incident['sic_vence_at']??'') ?></span></summary><p><?= nl2br(esc($incident['detalle'])) ?></p><div class="mini">Decision: <?= esc($incident['decision_reporte']??'pendiente') ?> · eventos inmutables: <?= count($incident['events']) ?></div><?php if($incident['estado']!=='cerrado'): ?><form class="compact-form" method="post" action="<?= base_url($basePath . '/seguridad/incidentes/actualizar') ?>"><?= csrf_field() ?><input type="hidden" name="incidente_id" value="<?= $incident['id'] ?>"><label>Actuacion</label><select name="action"><option value="classify">Clasificar</option><option value="contain">Contener/investigar</option><option value="decision">Decidir reporte</option><option value="report">Registrar reporte SIC</option><option value="communicate">Comunicar Titulares o motivar omision</option><option value="recover">Recuperar</option><option value="close">Cerrar</option></select><label>Severidad</label><select name="severidad"><?php foreach(['S1','S2','S3','S4'] as $v): ?><option <?= $incident['severidad']===$v?'selected':'' ?>><?= $v ?></option><?php endforeach; ?></select><label>Titulares estimados</label><input type="number" min="0" name="titulares_estimados"><label>Categorias afectadas</label><input name="categorias_afectadas"><label>Investigacion o contencion</label><textarea name="investigacion"></textarea><label>Decision de reporte</label><select name="decision_reporte"><option value="reportar">Reportar</option><option value="no_reportar">No reportar por no encuadrar</option></select><label>Motivacion</label><textarea name="decision_motivo"></textarea><label>Constancia SIC</label><input name="sic_evidencia"><label>Comunicacion a Titulares o motivo de omision</label><textarea name="titulares_comunicacion_motivo"></textarea><label>Lecciones aprendidas</label><textarea name="lecciones"></textarea><button class="btn btn-primary" type="submit">Registrar actuacion</button></form><?php endif; ?></details><?php endforeach; ?>
    <section class="card">
        <h3 style="margin-top:0">Usuarios y habilitacion</h3>
        <?php foreach($securityUsers as $user): ?>
            <div class="list-row"><strong><?= esc($user['nombre']) ?></strong> <span class="badge <?= (int)$user['activo']?'badge-on':'badge-off' ?>"><?= (int)$user['activo']?'activo':'inactivo' ?></span>
                <div class="mini"><?= esc($user['rol']) ?> · firma individual: <?= esc($user['confidencialidad_at']??'pendiente') ?> · induccion: <?= esc($user['induccion_at']??'pendiente') ?></div>
            </div>
        <?php endforeach; ?>
        <form method="post" action="<?= base_url($basePath . '/seguridad/usuarios') ?>">
            <?= csrf_field() ?><h4>Registrar induccion</h4><label>Usuario</label><select name="usuario_id" required><?php foreach($securityUsers as $user): ?><option value="<?= $user['id'] ?>"><?= esc($user['nombre'].' · '.$user['email']) ?></option><?php endforeach; ?></select>
            <label>Acta o evidencia verificable</label><input name="evidencia" required><button class="btn btn-primary" type="submit">Registrar induccion</button>
        </form>
    </section>
    <section class="card">
        <h3 style="margin-top:0">Generar compromiso individual</h3>
        <form method="post" action="<?= base_url($basePath . '/confidencialidad/generar') ?>">
            <?= csrf_field() ?><div class="form-grid">
                <div class="full"><label>Firmante</label><select name="usuario_id" required><option value="">Selecciona...</option><?php foreach($securityUsers as $user): ?><option value="<?= $user['id'] ?>"><?= esc($user['nombre'].' · '.$user['rol'].' · '.$user['email']) ?></option><?php endforeach; ?></select></div>
                <div><label>Tipo de documento</label><select name="tipo_documento"><option>CC</option><option>CE</option><option>PAS</option><option>PEP</option></select></div>
                <div><label>Numero de documento</label><input name="numero_documento" required></div>
                <div><label>Tipo de vinculo</label><select name="tipo_vinculo" required><?php foreach(['laboral','contratista','miembro_organo','temporal','tercero','proveedor_persona_natural'] as $value): ?><option value="<?= $value ?>"><?= esc(str_replace('_',' ',$value)) ?></option><?php endforeach; ?></select></div>
                <div><label>Rol operativo</label><select name="rol_operativo" required><?php foreach(['administracion','consejo','comite','porteria','vigilancia','mantenimiento','contabilidad','auditoria','soporte_ti','oficial_proteccion_datos'] as $value): ?><option value="<?= $value ?>"><?= esc(str_replace('_',' ',$value)) ?></option><?php endforeach; ?></select></div>
                <div><label>Vigente hasta</label><input type="date" name="vigencia_hasta" min="<?= date('Y-m-d',strtotime('+1 day')) ?>" max="<?= date('Y-m-d',strtotime('+12 months')) ?>" required></div>
                <div><label>Bases autorizadas</label><select name="bases[]" multiple size="6" required><?php foreach($bases as $base): ?><option value="<?= $base['id'] ?>"><?= esc($base['nombre']) ?></option><?php endforeach; ?></select></div>
                <div><label>Finalidades autorizadas</label><select name="finalidades[]" multiple size="6" required><?php foreach($finalidades as $purpose): ?><option value="<?= $purpose['id'] ?>"><?= esc($purpose['descripcion']) ?></option><?php endforeach; ?></select></div>
                <div class="full"><label>Operaciones permitidas</label><div class="checks"><?php foreach(['consultar','registrar','actualizar','exportar','suprimir','visualizar_cctv','operar_biometria'] as $operation): ?><label><input type="checkbox" name="operaciones[]" value="<?= $operation ?>"> <?= esc(str_replace('_',' ',$operation)) ?></label><?php endforeach; ?></div></div>
                <div class="full"><label>Justificacion si se autoriza todo el inventario</label><textarea name="alcance_total_justificacion"></textarea></div>
            </div><button class="btn btn-primary" type="submit">Generar y enviar para firma</button>
        </form>
    </section>
    <section class="card">
        <h3 style="margin-top:0">Instancias individuales</h3>
        <?php foreach($confidentialityAgreements as $agreement): ?><div class="list-row"><strong><?= esc($agreement['firmante_nombre']) ?></strong> <span class="badge <?= $agreement['estado']==='vigente'?'badge-on':(in_array($agreement['estado'],['cerrado','vencido'],true)?'badge-off':'') ?>"><?= esc($agreement['estado']) ?></span>
            <div class="mini">v<?= (int)$agreement['documento_version'] ?> · <?= esc($agreement['vigencia_desde']) ?> a <?= esc($agreement['vigencia_hasta']) ?> · hash <?= esc(substr($agreement['instancia_hash'],0,16)) ?> · copia <?= esc($agreement['copia_enviada_at']??'pendiente') ?></div>
            <?php if(in_array($agreement['estado'],['pendiente','vigente'],true)): ?><form class="compact-form" method="post" action="<?= base_url($basePath . '/confidencialidad/cerrar') ?>"><?= csrf_field() ?><input type="hidden" name="compromiso_id" value="<?= $agreement['id'] ?>"><label>Motivo de baja o cambio</label><input name="cierre_motivo" required><label>Certificacion de devolucion o eliminacion</label><input name="devolucion_evidencia" required><button class="btn btn-danger" type="submit">Revocar acceso y cerrar</button></form><?php endif; ?>
        </div><?php endforeach; ?>
    </section>
    <?php foreach($securityIncidents as $incident): if(empty($incident['sic_escalated']))continue; ?><div class="alert alert-error"><strong><?= esc($incident['folio']) ?> escalado:</strong> han transcurrido <?= (int)$incident['sic_elapsed_days'] ?> de 15 dias habiles sin constancia de reporte. Requiere atencion del Administrador y del Consejo.</div><?php endforeach; ?>
</section>
