<?php
$color = preg_match('/^#[0-9a-fA-F]{6}$/', (string) ($cliente['color_primario'] ?? '')) ? $cliente['color_primario'] : '#1f2937';
$activeDocuments = array_filter($documents, static fn ($d) => in_array($d['tipo'], ['politica', 'aviso'], true));
$guaranteeLabels = ['nivel_adecuado'=>'Pais con nivel adecuado de proteccion','declaracion_conformidad'=>'Declaracion de conformidad de la SIC','excepcion_articulo_26'=>'Excepcion del articulo 26 de la Ley 1581','autorizacion_expresa'=>'Autorizacion expresa del Titular'];
$housingProfiles = ['Propietario', 'Residente', 'Arrendatario', 'Menor de edad'];
?>
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Privacidad - <?= esc($cliente['nombre_tercero']) ?></title>
    <style>
        :root{--brand:<?= esc($color) ?>;--ink:#17202d;--line:#dfe3e8;--muted:#667085;--bg:#f4f6f8}*{box-sizing:border-box}body{margin:0;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif;color:var(--ink);background:var(--bg)}header{background:var(--brand);color:#fff;padding:22px max(18px,calc((100% - 980px)/2))}header h1{font-size:1.25rem;margin:0}header p{margin:5px 0 0;opacity:.86;font-size:.88rem}.wrap{max-width:980px;margin:0 auto;padding:22px 18px 42px}.intro{margin-bottom:18px}.intro h2{font-size:1.45rem;margin:0 0 6px}.intro p{color:var(--muted);margin:0;line-height:1.5}.tabs{display:inline-flex;background:#e6e9ee;padding:3px;border-radius:8px;margin-bottom:16px}.tabs button{border:0;background:transparent;padding:9px 14px;border-radius:6px;font-weight:700;cursor:pointer}.tabs button.active{background:#fff;box-shadow:0 1px 4px rgba(0,0,0,.1)}.pane{display:none}.pane.active{display:block}.section{background:#fff;border:1px solid var(--line);padding:22px;border-radius:8px;margin-bottom:14px}.section h3{margin:0 0 14px;font-size:1.05rem}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:13px}.full{grid-column:1/-1}label{display:block;font-size:.8rem;font-weight:700;margin-bottom:5px}input,select,textarea{width:100%;border:1.5px solid var(--line);border-radius:6px;padding:11px;font:inherit}textarea{min-height:100px}.choices{display:grid;gap:8px}.choice{display:flex;gap:9px;align-items:flex-start;border:1px solid var(--line);padding:11px;border-radius:6px}.choice input{width:auto;margin-top:3px}.choice label{margin:0;font-weight:500;line-height:1.4}.decision{display:flex;gap:8px;flex-wrap:wrap}.decision label{border:1px solid var(--line);padding:10px 12px;border-radius:6px;display:flex;gap:7px;align-items:center}.decision input{width:auto}.btn{border:0;background:var(--brand);color:#fff;font-weight:800;padding:11px 16px;border-radius:6px;cursor:pointer}.btn-secondary{background:#e9edf1;color:var(--ink);text-decoration:none;display:inline-block}.alert{padding:12px 14px;border-radius:6px;margin-bottom:14px}.success{background:#ecfdf3;color:#067647;border:1px solid #abefc6}.error{background:#fef2f2;color:#b42318;border:1px solid #fecaca}.docs{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.signature{border:1.5px solid var(--line);border-radius:6px;background:#fff;width:100%;height:170px;touch-action:none}.hint{color:var(--muted);font-size:.78rem;line-height:1.45}.locked{background:#f8fafc;border:1px solid var(--line);padding:15px;border-radius:6px;color:var(--muted)}@media(max-width:680px){.grid{grid-template-columns:1fr}.full{grid-column:auto}.tabs{display:flex}.tabs button{flex:1}.decision{display:grid}.decision label{width:100%}}
        .legal-preview{margin-top:14px;padding-top:14px;border-top:1px solid var(--line);font-size:.84rem;line-height:1.55;max-height:520px;overflow:auto}.legal-preview h1{font-size:1.25rem}.legal-preview h2{font-size:1rem;margin-top:18px}.legal-preview h3{font-size:.9rem;margin-top:14px}.legal-preview table{width:100%;border-collapse:collapse}.legal-preview th,.legal-preview td{border:1px solid var(--line);padding:6px}
    </style>
</head>
<body>
<header><h1><?= esc($cliente['nombre_tercero']) ?></h1><p>Canal de proteccion de datos personales</p></header>
<main class="wrap">
    <div class="intro"><h2>Gestiona tus datos personales</h2><p>Registra tu decision sobre el tratamiento o presenta una consulta, reclamo, rectificacion, revocatoria o solicitud de supresion.</p>
        <?php if($activeDocuments): ?><div class="docs"><?php foreach($activeDocuments as $document): ?><a class="btn btn-secondary" href="<?= base_url('privacidad/' . $token . '/documentos/' . $document['id']) ?>"><?= esc($document['titulo']) ?></a><?php endforeach; ?></div><?php endif; ?>
    </div>
    <?php if(!empty($confirmation)): ?><div class="alert success"><?= esc($confirmation) ?></div><?php endif; ?>
    <?php if(session('error')): ?><div class="alert error"><?= esc(session('error')) ?></div><?php endif; ?>
    <?php if(session('errors')): ?><div class="alert error"><ul><?php foreach(session('errors') as $error): ?><li><?= esc($error) ?></li><?php endforeach; ?></ul></div><?php endif; ?>
    <?php if(!$success): ?>
    <div class="tabs"><button type="button" data-tab="decision">Autorizacion</button><button type="button" data-tab="request">Ejercer derechos</button></div>
    <section class="pane" id="pane-decision">
        <?php if(!$authorization): ?><div class="locked">La autorizacion aun no tiene una version aprobada y publicada. Puedes presentar una solicitud mediante la opcion “Ejercer derechos”.</div>
        <?php elseif(!$verifiedIdentity): ?>
            <?php if($pendingVerification): ?><form class="section" method="post" action="<?= base_url('privacidad/' . $token . '/consentimiento/verificar') ?>"><?= csrf_field() ?><h3>Verificar correo</h3><p>Codigo enviado a <strong><?= esc($pendingVerification['email']) ?></strong>. Vence a las <?= esc($pendingVerification['expira_at']) ?>.</p><label>Codigo de seis digitos</label><input name="codigo" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" required><button class="btn" type="submit" style="margin-top:12px">Verificar identidad</button></form><?php endif; ?>
            <form class="section" method="post" enctype="multipart/form-data" action="<?= base_url('privacidad/' . $token . '/consentimiento/codigo') ?>"><?= csrf_field() ?><h3><?= $pendingVerification?'Solicitar un codigo nuevo':'Identificacion y legitimacion' ?></h3><div class="grid">
                <div><label>Perfil</label><select id="tipo_titular" name="tipo_titular" required><option value="">Seleccionar</option><?php foreach(['Propietario','Residente','Arrendatario','Visitante','Empleado','Proveedor','Contratista','Menor de edad','Otro'] as $profile): ?><option value="<?= esc($profile) ?>" <?= old('tipo_titular')===$profile?'selected':'' ?>><?= esc($profile) ?></option><?php endforeach; ?></select></div>
                <div id="housing-unit-field"><label>Unidad habitacional</label><select id="inmueble_id" name="inmueble_id"><option value="">Seleccionar torre y unidad...</option><?php $unitGroup=null; foreach($housingUnits as $unit): $group=$unit['torre_nombre']?:'Casas'; if($group!==$unitGroup): if($unitGroup!==null): ?></optgroup><?php endif; ?><optgroup label="<?= esc($group) ?>"><?php $unitGroup=$group; endif; ?><option value="<?= (int)$unit['id'] ?>" <?= (string)old('inmueble_id')===(string)$unit['id']?'selected':'' ?>><?= esc(($unit['torre_nombre']?$unit['torre_nombre'].' - ':'').$unit['identificador']) ?></option><?php endforeach; if($unitGroup!==null): ?></optgroup><?php endif; ?></select><p class="hint">Obligatoria para propietarios, residentes, arrendatarios y menores. Permite a la administracion medir cobertura por apartamento o casa.</p></div>
                <div><label>Nombre completo del Titular</label><input name="titular_nombre" required value="<?= old('titular_nombre') ?>"></div><div><label>Tipo de documento</label><select name="titular_tipo_documento"><option>CC</option><option>CE</option><option>Pasaporte</option><option>TI</option></select></div><div><label>Numero de documento</label><input name="titular_documento" required value="<?= old('titular_documento') ?>"></div><div><label>Correo que se verificara</label><input type="email" name="titular_email" required value="<?= old('titular_email') ?>"></div><div><label>Actua en calidad de</label><select name="calidad_otorgante" required><option value="titular">Titular</option><option value="representante_menor">Representante legal de menor</option><option value="apoderado">Apoderado</option></select></div><div><label>Nombre del representante o apoderado</label><input name="representante_nombre"></div><div><label>Documento del representante o apoderado</label><input name="representante_documento"></div><div><label>Calidad de representacion</label><input name="calidad_representacion" placeholder="Madre, padre, tutor o apoderado"></div><div><label>Registro civil, poder o soporte</label><input type="file" name="soporte_representacion" accept="image/jpeg,image/png,application/pdf"></div><div class="full"><label>Constancia de escucha y valoracion de la opinion del menor</label><textarea name="opinion_menor"></textarea></div>
            </div><button class="btn" type="submit">Enviar codigo de verificacion</button></form>
        <?php elseif($consentPreview): ?><div class="section"><h3>Instancia final para firma</h3><div class="legal-preview"><?= $consentPreview['instance'] ?></div><p class="hint">SHA-256 de esta instancia: <?= esc($consentPreview['instance_hash']) ?></p></div><form method="post" action="<?= base_url('privacidad/' . $token . '/consentimiento') ?>" id="consent-form"><?= csrf_field() ?><input type="hidden" name="action" value="confirm"><input type="hidden" name="documento_hash" value="<?= esc($authorization['hash_sha256']) ?>"><?php foreach($consentPreview['decision_vector'] as $key=>$record): $decision=$record['decision']; if(($record['tipo']??'')==='finalidad'): ?><input type="hidden" name="finalidad_decision[<?= esc($key) ?>]" value="<?= esc($decision) ?>"><?php elseif(($record['tipo']??'')==='dato_sensible'): ?><input type="hidden" name="sensible_decision[<?= esc(substr($key,9)) ?>]" value="<?= esc($decision) ?>"><?php elseif($key==='biometria'): ?><input type="hidden" name="biometria_decision" value="<?= esc($decision) ?>"><?php elseif($key==='transferencia_internacional'): ?><input type="hidden" name="transferencia_decision" value="<?= esc($decision) ?>"><?php elseif($key==='menor'): ?><input type="hidden" name="menor_decision" value="<?= esc($decision) ?>"><?php endif; endforeach; ?><div class="section"><h3>Firma de la instancia revisada</h3><canvas class="signature" id="signature"></canvas><input type="hidden" name="firma_imagen" id="firma_imagen"><button class="btn btn-secondary" type="button" id="clear-signature" style="margin-top:8px">Limpiar firma</button></div><button class="btn" type="submit">Firmar y registrar decision</button></form>
        <?php else: ?><form method="post" action="<?= base_url('privacidad/' . $token . '/consentimiento') ?>">
            <?= csrf_field() ?>
            <input type="hidden" name="action" value="preview">
            <input type="hidden" name="documento_hash" value="<?= esc($authorization['hash_sha256']) ?>">
            <details class="section"><summary><strong>Texto completo de la autorizacion vigente · version <?= esc($authorization['version']) ?></strong></summary><div class="legal-preview" style="margin-top:14px"><?= $authorization['contenido_html'] ?></div><p class="hint">SHA-256: <?= esc($authorization['hash_sha256']) ?></p></details>
            <div class="section"><h3>Identidad verificada</h3><p><strong><?= esc($verifiedIdentity['titular_nombre']) ?></strong><br><?= esc($verifiedIdentity['titular_tipo_documento'].' '.$verifiedIdentity['titular_documento']) ?><br><?= esc($verifiedIdentity['titular_email']) ?><?php if(!empty($verifiedIdentity['inmueble_label'])): ?><br>Unidad: <?= esc($verifiedIdentity['inmueble_label']) ?><?php endif; ?><br>Calidad: <?= esc($verifiedIdentity['calidad_otorgante']) ?></p></div>
            <?php if($informedPurposes): ?><div class="section"><h3>Tratamientos informados que no dependen de esta autorizacion</h3><div class="choices"><?php foreach($informedPurposes as $purpose): ?><div class="choice"><div><strong><?= esc($purpose['base_nombre']) ?></strong><br><?= esc($purpose['descripcion']) ?><br><span class="hint">Base legal: <?= esc($purpose['base_juridica_detalle']) ?></span></div></div><?php endforeach; ?></div><p class="hint">Conservas los derechos de conocer, actualizar, rectificar y reclamar sobre estos tratamientos.</p></div><?php endif; ?>
            <div class="section"><h3>Decisiones por finalidad</h3><div class="choices"><?php foreach($consentPurposes as $purpose): $categories=json_decode($purpose['categorias_datos_json'] ?? '[]',true)?:[]; ?><div class="choice"><div style="width:100%"><strong><?= esc($purpose['base_nombre']) ?> · <?= esc($purpose['descripcion']) ?></strong><p class="hint">Datos comunes: <?= esc(implode(', ',$categories)) ?>. <?= (int)$purpose['es_opcional']?'OPCIONAL. Si no autorizas: '.esc($purpose['consecuencia_negativa']).'. Ninguna otra consecuencia es aplicable.':'Necesaria para la relacion informada.' ?></p><div class="decision"><label><input type="radio" name="finalidad_decision[<?= $purpose['id'] ?>]" value="autoriza" required> Autorizo</label><label><input type="radio" name="finalidad_decision[<?= $purpose['id'] ?>]" value="no_autoriza" required> No autorizo</label></div></div></div><?php endforeach; ?></div></div>
            <?php if($sensitiveItems): ?><div class="section"><h3>Decisiones separadas sobre datos sensibles</h3><p class="hint">Responder es facultativo. Cada dato tiene finalidad exclusiva y puede negarse sin consecuencias adversas.</p><div class="choices"><?php foreach($sensitiveItems as $item): ?><div class="choice"><div style="width:100%"><strong><?= esc($item['dato']) ?></strong><p><?= esc($item['finalidad_exclusiva']) ?></p><div class="decision"><label><input type="radio" name="sensible_decision[<?= $item['id'] ?>]" value="autoriza" required> Autorizo expresamente</label><label><input type="radio" name="sensible_decision[<?= $item['id'] ?>]" value="no_autoriza" required> No autorizo</label></div></div></div><?php endforeach; ?></div></div><?php endif; ?>
            <?php if(!empty($config['usa_biometria']) || !empty($config['video_identificacion_biometrica'])): ?><div class="section"><h3>Decision separada sobre biometria</h3><p>Dato: <strong><?= esc($config['tipo_biometria'] ?? '') ?></strong>. Finalidad exclusiva: <?= esc($config['finalidad_biometria'] ?? '') ?>. Este dato es sensible y responder es facultativo.</p><p>Alternativa permanente, gratuita y sin restriccion de acceso: <strong><?= esc($config['alternativa_biometrica'] ?? '') ?></strong>.</p><div class="decision"><label><input type="radio" name="biometria_decision" value="autoriza" required> Autorizo expresamente</label><label><input type="radio" name="biometria_decision" value="no_autoriza" required> No autorizo; usare la alternativa</label></div></div><?php endif; ?>
            <?php if(!empty($config['transferencia_internacional']) && !empty($config['transferencia_requiere_autorizacion'])): ?><div class="section"><h3>Decision sobre transferencia internacional</h3><p>Receptor: <strong><?= esc($config['receptor_exterior']??'') ?></strong>. Pais: <?= esc($config['paises_transferencia']??'') ?>. Garantia: <?= esc($guaranteeLabels[$config['garantia_transferencia']??'']??'') ?> <?= esc($config['garantia_transferencia_detalle']??'') ?>.</p><div class="decision"><label><input type="radio" name="transferencia_decision" value="autoriza" required> Autorizo expresamente</label><label><input type="radio" name="transferencia_decision" value="no_autoriza" required> No autorizo</label></div></div><?php endif; ?>
            <?php if(($verifiedIdentity['calidad_otorgante']??'')==='representante_menor'): ?><div class="section"><h3>Decision del representante legal</h3><p>La decision se adopta en el interes superior del menor, respetando sus derechos prevalentes y la opinion registrada durante la identificacion.</p><div class="decision"><label><input type="radio" name="menor_decision" value="autoriza" required> Autorizo como representante legal</label><label><input type="radio" name="menor_decision" value="no_autoriza" required> No autorizo</label></div></div><?php endif; ?>
            <div class="section"><h3>Evidencia</h3><p class="hint">Antes de firmar veras la instancia final completa y su hash SHA-256. Se conservaran el vector de decisiones, fecha y hora del servidor, zona horaria, canal, IP e identificador del navegador con finalidad probatoria. No se captura geolocalizacion ni huella ampliada del dispositivo. Recibiras copia por <?= esc($config['canal_entrega_copia'] ?? 'correo electronico') ?>.</p></div>
            <button class="btn" type="submit">Generar instancia para revision y firma</button>
        </form><?php endif; ?>
    </section>
    <section class="pane" id="pane-request"><form method="post" action="<?= base_url('privacidad/' . $token . '/solicitud') ?>"><?= csrf_field() ?>
        <div class="section"><h3>Solicitud</h3><div class="grid"><div><label>Tipo</label><select name="tipo" required><option value="consulta">Consulta o acceso</option><option value="reclamo">Reclamo</option><option value="rectificacion">Rectificacion</option><option value="actualizacion">Actualizacion</option><option value="revocatoria">Revocatoria</option><option value="supresion">Supresion</option></select></div><div><label>Calidad</label><select name="calidad_solicitante"><option value="titular">Titular</option><option value="representante">Representante</option><option value="causahabiente">Causahabiente</option><option value="representante_menor">Representante de menor</option></select></div><div><label>Nombre completo</label><input name="titular_nombre" required></div><div><label>Documento</label><input name="titular_documento"></div><div><label>Correo de respuesta</label><input type="email" name="titular_email" required></div><div><label>Soporte de legitimacion</label><input name="legitimacion_tipo" placeholder="Poder, registro civil u otro"></div><div class="full"><label>Peticion; para reclamos indica hechos</label><textarea name="solicitud_texto"></textarea></div></div></div><button class="btn" type="submit">Radicar solicitud</button>
    </form></section>
    <?php endif; ?>
</main>
<script>
(function(){var tabs=[].slice.call(document.querySelectorAll('[data-tab]'));function openTab(name){tabs.forEach(function(t){t.classList.toggle('active',t.dataset.tab===name)});document.querySelectorAll('.pane').forEach(function(p){p.classList.toggle('active',p.id==='pane-'+name)})}tabs.forEach(function(t){t.addEventListener('click',function(){openTab(t.dataset.tab)})});openTab('decision');var profile=document.getElementById('tipo_titular'),unit=document.getElementById('inmueble_id'),unitField=document.getElementById('housing-unit-field'),housingProfiles=<?= json_encode($housingProfiles, JSON_UNESCAPED_UNICODE) ?>;function syncUnit(){if(!profile||!unit||!unitField)return;var required=housingProfiles.indexOf(profile.value)!==-1;unit.required=required;unitField.style.display=required?'block':'none';if(!required)unit.value=''}if(profile){profile.addEventListener('change',syncUnit);syncUnit()}var canvas=document.getElementById('signature');if(!canvas)return;var ctx=canvas.getContext('2d'),drawing=false,dirty=false;function resize(){var rect=canvas.getBoundingClientRect(),copy=dirty?canvas.toDataURL():null;canvas.width=Math.max(1,Math.round(rect.width*devicePixelRatio));canvas.height=Math.max(1,Math.round(rect.height*devicePixelRatio));ctx=canvas.getContext('2d');ctx.scale(devicePixelRatio,devicePixelRatio);ctx.lineWidth=2;ctx.lineCap='round';ctx.strokeStyle='#17202d';if(copy){var img=new Image();img.onload=function(){ctx.drawImage(img,0,0,rect.width,rect.height)};img.src=copy}}function point(e){var r=canvas.getBoundingClientRect(),t=e.touches?e.touches[0]:e;return{x:t.clientX-r.left,y:t.clientY-r.top}}function start(e){drawing=true;dirty=true;var p=point(e);ctx.beginPath();ctx.moveTo(p.x,p.y);e.preventDefault()}function move(e){if(!drawing)return;var p=point(e);ctx.lineTo(p.x,p.y);ctx.stroke();e.preventDefault()}function end(){drawing=false}canvas.addEventListener('pointerdown',start);canvas.addEventListener('pointermove',move);window.addEventListener('pointerup',end);document.getElementById('clear-signature').addEventListener('click',function(){ctx.clearRect(0,0,canvas.width,canvas.height);dirty=false});document.getElementById('consent-form').addEventListener('submit',function(){document.getElementById('firma_imagen').value=dirty?canvas.toDataURL('image/png'):''});resize();window.addEventListener('resize',resize)})();
</script>
</body></html>
